### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by jahirfiquitiva** [GregHilston/Simple-Slack-Bot#25]
Hello

Thanks for creating this awesome tool/lib ...

I want to deploy my slack bot to heroku but I don't know how to (new to Heroku), would you mind helping me with that?

Thanks in advance :)

**Comment by GregHilston** [comment]
Hey @jahirfiquitiva thanks for being interest in the library!

I actually have never used heroku, that being said I looked up the:

> Deploy to Heroku

button that can be added to a `README.md` and might consider adding that.

I don't think adding that button makes sense for this specific repo, as its a library, but may add that to one of the example Simple Slack Bots 

- [Ping Pong Bot](https://github.com/GregHilston/Ping-Pong-Bot)
- [The Office Bot](https://github.com/GregHilston/The-Office-Bot)

that someone could fork and replace with their own logic.

As this isn't a priority for me, I'll ping you or reply to this issue if I complete this. 

By all means, you're welcome to submit a PR to this library or the two projects listed above!

**Comment by jahirfiquitiva** [comment]
Hi @GregHilston 

Thanks for the help. I forgot to update this issue. I have solved this already and it can be seen in my [Stan Bot](https://github.com/jahirfiquitiva/StanBot)

If you want to, feel free to close this issue.

Thanks again 😄

**Comment by GregHilston** [comment]
Excellent @jahirfiquitiva !

Do you mind if I put a link to your bot in the Simple-Slack-Bot `README.md`?

Specifically the "Simple Slack Bots" section

**Comment by jahirfiquitiva** [comment]
@GregHilston Of course I don't 😄 Feel free to do so 😊

**Comment by GregHilston** [comment]
Awesome! @jahirfiquitiva I added it and will close this issue!

If you ever have any ideas for this library, please let me know or submit a PR
