### ISSUE TITLE
Prevent bot crash

### ISSUE THREAD

**Issue by andrew-boutin** [GregHilston/Simple-Slack-Bot#28]
Could you add some error handling logic so the bot will log an error message and continue to process requests if an exception occurs in a callback?

**Comment by GregHilston** [comment]
Yes, good idea!

**Comment by andrew-boutin** [comment]
What do you think about moving the try logic around processing a single event instead of a batch of events?

This would make it so the first event causing an exception in a batch of events wouldn't prevent the next event from being processed.

https://github.com/GregHilston/Simple-Slack-Bot/commit/d436866781e75336de04c4f993d541d5a3e619c0#r30099833
