### ISSUE TITLE
"not_allowed_token_type" error

### ISSUE THREAD

**Issue by paolovacirca** [GregHilston/Simple-Slack-Bot#37]
I got it all to work perfectly. Then I made a new bot, created a new oAuth token, and now it doesn't work any more. I can't recall doing anything differently this time. Any idea of what might be wrong? I'm getting this:

slacksocket.errors.SlackAPIError: Error from slack api:
 {"ok":false,"error":"not_allowed_token_type"}

**Comment by GregHilston** [comment]
Hey @MrOaiki, can you share your application code here?

Also, you mentioned a 

> new oAuth token

For clarity, we want to use a 

> API Token, The library you are using will want an API token for your bot.

Which you can generate from https://[your-slack-team].slack.com/apps/manage/custom-integrations

**Comment by GregHilston** [comment]
Closing due to lack of additional information. @MrOaiki feel free to comment or open a new issue!
