### ISSUE TITLE
Errors when trying to run example_component.py

### ISSUE THREAD

**Issue by coltenkrauter** [GregHilston/Simple-Slack-Bot#41]
I am trying to run [example_component.py](https://github.com/GregHilston/Simple-Slack-Bot/blob/master/example_component.py) and I have supplied a `slack_bot_token`. 

I am getting the following error:

```bash
initialized. Ready to connect
registering callback hello_callback to event type hello
registering callback user_typing_callback to event type user_typing
registering callback pong_callback to event type message
Traceback (most recent call last):
  File "example_component.py", line 28, in <module>
    main()
  File "example_component.py", line 24, in main
    simple_slack_bot.start()
  File ".../Simple-Slack-Bot/simple_slack_bot/simple_slack_bot.py", line 182, in start
    ok = self._slacker.rtm.start().body["ok"]
AttributeError: 'NoneType' object has no attribute 'rtm'
```

I poked through the code a bit and I discovered that `_slacker` was **None** because the connect function hadn't been called yet. 

So, I simply added a call to `connect()` before the call to `start()` and that fixed that error for me.

```python
def main():
    simple_slack_bot.connect()
    simple_slack_bot.start()
```

Is this expected behavior? I notice that the example in the README doesn't call `connect()` before it calls `start()`.

**Comment by coltenkrauter** [comment]
Spoke too soon, now I am getting a new error. 

```bash
initialized. Ready to connect
registering callback hello_callback to event type hello
registering callback user_typing_callback to event type user_typing
registering callback pong_callback to event type message
Connecting...
Traceback (most recent call last):
  File "example_component.py", line 29, in <module>
    main()
  File "example_component.py", line 24, in main
    simple_slack_bot.connect()
  File ".../Simple-Slack-Bot/simple_slack_bot/simple_slack_bot.py", line 79, in connect
    self._slackSocket = SlackSocket(self._SLACK_BOT_TOKEN, translate=False)
  File ".../Simple-Slack-Bot/venv/lib/python3.7/site-packages/slacksocket/client.py", line 50, in __init__
    self._load_channels()
  File ".../Simple-Slack-Bot/venv/lib/python3.7/site-packages/slacksocket/client.py", line 271, in _load_channels
    response = self._call_slack_rtm(slackurl[channel_type])
  File ".../Simple-Slack-Bot/venv/lib/python3.7/site-packages/slacksocket/client.py", line 421, in _call_slack_rtm
    raise errors.SlackAPIError('Error from slack api:\n %s' % res.text)
slacksocket.errors.SlackAPIError: Error from slack api:
 {"ok":false,"error":"method_deprecated","response_metadata":{"messages":["[ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead. Learn more: https:\/\/api.slack.com\/changelog\/2020-01-deprecating-antecedents-to-the-conversations-api."]}}
```

**[ERROR] This method is retired and can no longer be used. Please use conversations.list or users.conversations instead.**

@GregHilston Am I doing something wrong?
I cloned your repo **Simple-Slack-Bot** and then switched to the **support-channel-replies** branch.

Here is the code I am trying to run in a Python virtual env,

```python
from simple_slack_bot.simple_slack_bot import SimpleSlackBot

simple_slack_bot = SimpleSlackBot(debug=True, slack_bot_token='xoxb-a token was here')


@simple_slack_bot.register("hello")
def hello_callback(request):
    request.write("Hello!")


@simple_slack_bot.register("user_typing")
def user_typing_callback(request):
    user_id = simple_slack_bot.helper_user_id_to_user_name(request._slack_event.event['user'])
    request.write(f"I see you typing {user_id}")


@simple_slack_bot.register("message")
def pong_callback(request):
    if request.message and request.message.lower() == "ping":
        request.write("Pong")


def main():
    simple_slack_bot.connect()
    simple_slack_bot.start()


if __name__ == "__main__":
    main()
```

Python 3.7.3


```bash
$ pip freeze

appdirs==1.4.0
bleach==3.1.4
certifi==2019.11.28
chardet==3.0.4
docutils==0.16
idna==2.7
importlib-metadata==1.6.0
keyring==21.2.0
packaging==16.8
pkginfo==1.5.0.1
Pygments==2.6.1
pyparsing==2.1.10
PyYAML==5.1
readme-renderer==25.0
requests==2.20.0
requests-toolbelt==0.9.1
six==1.10.0
slackclient==1.0.2
slacker==0.14.0
slacksocket==0.7
tqdm==4.45.0
twine==3.1.1
urllib3==1.24.3
webencodings==0.5.1
websocket-client==0.40.0
zipp==3.1.0
```

**Comment by jcastro-sfdc** [comment]
@coltenkrauter @GregHilston You are not doing anything wrong.  The groups, im, channels and mpim API methods are deprecated and will disappear all together in Feb 2021.  Any new app(bot) will not be able to call those methods at all.  Any bot created before June 10, 2020 will still be able to call them but you'll get warnings to start using the conversations method before Feb 2021.  Have a look at this article.  https://api.slack.com/changelog

I ran into this issue with errbot and created a PR with the correct methods https://github.com/errbotio/errbot/pull/1438.

When I have time I can take a look at your code and do the same.  I like what I see here and want to test this for our team.

**Comment by jcastro-sfdc** [comment]
so I just noticed that you are using the slacker package.  My recommendation would be to move to the https://github.com/slackapi/python-slackclient package.  The slacker package is archived.

**Comment by GregHilston** [comment]
@jcastro-sfdc Sorry about such a late reply, life has been busy lately ha 

Understood. Excellent find. 

I will add this to the issues for this project and target this next time I work on this project. 

To anyone else reading this, any and all PRs are welcome :)

Thanks for the great investigation work @jcastro-sfdc  :)

**Comment by GregHilston** [comment]
@coltenkrauter and @jcastro-sfdc can you both look at #44  if your time allows? This should resolve our issues listed here and in issue #42
