### ISSUE TITLE
Deployment Patterns?

### ISSUE THREAD

**Issue by ankur-hop** [GregHilston/Simple-Slack-Bot#48]
Hi -- 

Love the bot, great work, thank you for open-sourcing it. Really appreciate the code coverage and thorough usage of modern Python development tools.

Quick question -- what deployment pattern do you recommend for this? Is this something you typically export out as a Lambda behind API Gateway? Is there a simpler pattern?

Thanks!

Ankur

**Comment by GregHilston** [comment]
Hey @ankur-hop! Great question!

I would not recommend Lambda or other serverless patterns as this framework does take advantage of blocking on a web socket connection. Therefore, I'd recommend deploying this on a very small instance like an AWS `t2.micro` or even a Digital Ocean $5/month droplet.

I've been using a Home Server, always on desktop, for development and that has worked great.

I recently merged in a PR that adds a sample `Dockerfile` which might be a good jumping off point!
